# Generated by Django 4.2.3 on 2023-07-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreman',
            name='hired_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='foreman',
            name='salary',
            field=models.FloatField(null=True),
        ),
    ]
