# Generated by Django 4.2.3 on 2023-07-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0002_alter_foreman_hired_date_alter_foreman_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='products_produced',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='workman',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
    ]
