# Generated by Django 4.2.3 on 2023-07-18 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0003_alter_shift_products_produced_alter_workman_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foreman',
            options={'ordering': ['username'], 'verbose_name': 'foreman', 'verbose_name_plural': 'foreman'},
        ),
        migrations.AlterField(
            model_name='shift',
            name='foreman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='foreman_to_day', to=settings.AUTH_USER_MODEL),
        ),
    ]
