# Generated by Django 4.2.3 on 2023-07-18 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0004_alter_foreman_options_alter_shift_foreman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workman',
            name='commitment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_commitment', to='hall.workcommitments'),
        ),
    ]
