# Generated by Django 4.2.3 on 2023-07-18 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0006_alter_shift_foreman'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['work_date']},
        ),
        migrations.AlterModelOptions(
            name='workman',
            options={'ordering': ['first_name']},
        ),
    ]
